# GitLab user. git by default
user: git

# Url to gitlab instance. Used for api calls
gitlab_url: "http://localhost/"

# Repositories path
repos_path: "/var/lib/gitlab/repositories"

# File used as authorized_keys for gitlab user
auth_file: "/var/lib/gitlab/.ssh/authorized_keys"
